alchemyplatform/rundler

.github/workflows/ci.yaml
.github/workflows/codecov.yaml
.github/workflows/unit.yaml

- Add codecov to the CI test runner

chore(codecov): add codecov reporting for CI pipeline

---

crates/builder/src/signer/aws.rs

- Attempts to re-lock lost locks, instead of looping trying to extend them

fix(builder): attempt to re-lock lost key locks

---

src/common/types/chain.rs

- Add arb sepolia id to list of chains needed for logic

feat(arb-sepolia): add arb sepolia to list of chain ids

---

crates/types/src/chain.rs

- Make sure release changes are also in main branch

feat(arb): match release with main

---

crates/builder/src/bundle_sender.rs
crates/builder/src/transaction_tracker.rs

fix(builder): allow for none transaction receipt

---

README.md

fix(docs): duplicate wording in readme

---

crates/pool/proto/op_pool/op_pool.proto
crates/pool/src/mempool/mod.rs
crates/pool/src/mempool/reputation.rs
crates/pool/src/mempool/uo_pool.rs
crates/pool/src/server/local.rs
crates/pool/src/server/mod.rs
crates/pool/src/server/remote/client.rs
crates/pool/src/server/remote/protos.rs
crates/pool/src/server/remote/server.rs
crates/rpc/src/debug.rs
crates/rpc/src/eth/error.rs
crates/rpc/src/types.rs
crates/sim/src/simulation/simulation.rs
crates/sim/src/simulation/tracer.rs
crates/sim/tracer/src/validationTracer.ts

Closes #531 
- Seperated read and write access from tracer
- change tracer parsing logic to follow similar implementation as the reference bundler https://github.com/eth-infinitism/bundler/blob/ba78f2067e33df399bb7d34a9d1f972834d23c80/packages/validation-manager/src/TracerResultParser.ts#L315
- Changed error codes to work with spec tests
- Update error message to work with spec tests

feat(compliance): fixes for spec tests

---

crates/pool/proto/op_pool/op_pool.proto
crates/pool/src/lib.rs
crates/pool/src/mempool/mod.rs
crates/pool/src/mempool/uo_pool.rs
crates/pool/src/server/local.rs
crates/pool/src/server/mod.rs
crates/pool/src/server/remote/client.rs
crates/pool/src/server/remote/protos.rs
crates/pool/src/server/remote/server.rs
crates/pool/src/task.rs
crates/provider/src/ethers/mod.rs
crates/provider/src/ethers/stake_manager.rs
crates/provider/src/lib.rs
crates/provider/src/traits/stake_manager.rs
crates/rpc/src/debug.rs
crates/rpc/src/types.rs
crates/types/build.rs
crates/types/src/lib.rs

Closes #538 
- create debug method for stake status to match reference bundler

feat(compliance): add debug method for stake status

---

bin/rundler/src/cli/mod.rs
crates/builder/src/bundle_proposer.rs
crates/builder/src/emit.rs
crates/builder/src/transaction_tracker.rs
crates/pool/src/mempool/uo_pool.rs
crates/provider/src/ethers/provider.rs
crates/provider/src/traits/provider.rs
crates/rpc/src/eth/api.rs
crates/rpc/src/rundler.rs
crates/rpc/src/task.rs
crates/sim/src/estimation/estimation.rs
crates/sim/src/gas/gas.rs
crates/sim/src/gas/oracle.rs
crates/sim/src/precheck.rs

Cherry-pick https://github.com/alchemyplatform/rundler/commit/fec0cb7ea54ff599787955d3abfe0c53eaf726e8

feat: change priority fee strategy

---

docs/cli.md

chore(docs): add RUST_LOG to docs

---

crates/sim/src/gas/gas.rs
crates/sim/src/gas/oracle.rs
docs/architecture/builder.md
docs/architecture/pool.md
docs/architecture/rpc.md

Cherry-picked from https://github.com/alchemyplatform/rundler/commit/3fa4c6b8feb956fea790ba18c448b57ce054e8f2

feat: use usage based oracle on polygon

---

.github/workflows/ci.yaml
Cargo.toml
Dockerfile
bin/rundler/src/cli/builder.rs
bin/rundler/src/cli/node/mod.rs
bin/rundler/src/cli/pool.rs
crates/sim/src/simulation/simulation.rs

Cherry pick of https://github.com/alchemyplatform/rundler/pull/554

chore: update to rust 1.75

---

crates/builder/src/bundle_sender.rs
crates/builder/src/sender/bloxroute.rs
crates/builder/src/sender/conditional.rs
crates/builder/src/sender/flashbots.rs
crates/builder/src/sender/mod.rs
crates/builder/src/sender/raw.rs
crates/builder/src/transaction_tracker.rs
crates/types/src/gas.rs
crates/utils/src/math.rs

Relates to #550
See https://github.com/alchemyplatform/rundler/pull/553

fix(builder): try underpriced bundle txns again

---

crates/rpc/src/eth/error.rs

There is a test in the spec tests that checks to make sure the reputation status is in the error message. For one of the cases our bunder does not pass as we need the "unstaked" keyword in the error message and an addition change of error code to the stake too low error code.
https://github.com/eth-infinitism/bundler-spec-tests/blob/2b396495ad4bb526c0a0ad39d3795068a142cd2d/tests/single/bundle/test_bundle.py#L233
- Update error code
- Add "unstaked" to error

feat(compliance): change error code and add unstaked keyword to error message

---

crates/pool/src/mempool/uo_pool.rs

Closes #498
- Only update reputation if op is not a replacement

fix(reputation): do not increase ops seen on replacement

---

crates/pool/src/chain.rs
crates/pool/src/mempool/paymaster.rs
crates/pool/src/mempool/pool.rs
crates/pool/src/mempool/uo_pool.rs

Closes #561 
- Use the same logic as the entity deposits but look for withdrawal logs instead

feat(paymaster): add paymaster withdrawal logic to tracker

---

Cargo.lock
Cargo.toml
bin/rundler/Cargo.toml
bin/rundler/src/cli/pool.rs
crates/builder/Cargo.toml
crates/builder/src/sender/mod.rs
crates/sim/Cargo.toml
crates/sim/src/estimation/estimation.rs
crates/sim/src/gas/gas.rs
crates/sim/src/precheck.rs
crates/types/Cargo.toml
crates/types/src/chain.rs

Cherrypicked from bdf15108afafbc4f44c7b774a47b276b20e682e8

feat(chains): add polygon amoy and use alloy-rs (#583)

---

crates/sim/tracer/src/validationTracer.ts

Cherry picked from 0b2aa762432d35236839df6d6a50a7b26cec16a7

feat(tracer): add RIP-7212 precompile (#586)

---

crates/pool/src/server/remote/server.rs

fix(pool): fix proto reputation status conversion

---

crates/pool/src/server/remote/error.rs

fix(pool): fix remote pool error conversion

---

crates/pool/proto/op_pool/op_pool.proto
crates/pool/src/mempool/mod.rs
crates/pool/src/mempool/paymaster.rs
crates/pool/src/mempool/pool.rs
crates/pool/src/mempool/uo_pool.rs
crates/pool/src/server/local.rs
crates/pool/src/server/mod.rs
crates/pool/src/server/remote/client.rs
crates/pool/src/server/remote/protos.rs
crates/pool/src/server/remote/server.rs
crates/rpc/src/admin.rs
crates/rpc/src/debug.rs
crates/rpc/src/types.rs
docs/architecture/rpc.md

Closes #573 
- Add new debug RPC method to dump and paymaster balances
- Wire it all up

feat: add debug rpc method to dump paymaster balances from pool

---

Cargo.lock
Cargo.toml
bin/rundler/src/cli/pool.rs
crates/pool/Cargo.toml
crates/pool/src/mempool/mod.rs
crates/pool/src/mempool/paymaster.rs
crates/pool/src/mempool/uo_pool.rs
crates/pool/src/task.rs
crates/utils/Cargo.toml
crates/utils/src/cache.rs
crates/utils/src/lib.rs
docs/cli.md

Closes #520 
- Adds a LRU cache to the paymaster tracker to expire paymasters

feat(pool): add paymaster lru cache

---

crates/sim/src/simulation/simulation.rs

- Adds support for the new [OP-080 rule](https://github.com/eth-infinitism/account-abstraction/pull/460)
- Merge pending on the ERC-7562 PR merging

feat(sim): add support for op-080

---

crates/sim/src/estimation/estimation.rs

- Handles AA51 as out of gas during validation gas estimation
- Also fixes the fee logic to not rely on the base fee, uses pre-1559 mechanics

fix(sim): handle aa51 as OOG in estimation

---

.github/scripts/compliance_parser.sh
.github/workflows/compliance.yaml

- Add coompliance tests back to repo and use script to parse results

feat(spec): add compliance back

---

crates/sim/src/simulation/simulation.rs

- Return correct entity type for stake violation
- Leave in previous logic for a fallback

fix(sim): update storage access rules to return correct entity

---

crates/pool/proto/op_pool/op_pool.proto
crates/pool/src/server/remote/client.rs
crates/pool/src/server/remote/error.rs
crates/pool/src/server/remote/protos.rs
crates/task/src/grpc/protos.rs
crates/types/src/user_operation/v0_7.rs

- Cleans up some protobuf serde methods
- Adds support for EP 0.7 to the protobuf conversions

feat: add remote support for v0.7

---

bin/rundler/src/cli/builder.rs
crates/builder/src/lib.rs
crates/builder/src/task.rs
crates/provider/src/ethers/entry_point/v0_6.rs
crates/provider/src/lib.rs
crates/provider/src/traits/entry_point.rs
crates/provider/src/traits/mod.rs

- Start adding support for multiple entry point versions in builder
- Further progress here is blocked by:
- Entry point provider v0.7
- Simulation v0.7

feat(builder): start support for multiple entry points in builder

---

bin/rundler/src/cli/builder.rs
bin/rundler/src/cli/pool.rs
crates/builder/src/task.rs
crates/pool/src/chain.rs
crates/pool/src/mempool/paymaster.rs
crates/pool/src/task.rs
crates/provider/src/ethers/entry_point/mod.rs
crates/provider/src/ethers/entry_point/v0_6.rs
crates/provider/src/ethers/entry_point/v0_7.rs
crates/provider/src/traits/entry_point.rs
crates/provider/src/traits/test_utils.rs
crates/rpc/src/task.rs
crates/sim/src/estimation/v0_6.rs
crates/sim/src/gas/gas.rs
crates/sim/src/lib.rs
crates/sim/src/precheck.rs
crates/sim/src/simulation/mempool.rs
crates/sim/src/simulation/mod.rs
crates/types/src/user_operation/mod.rs
crates/types/src/user_operation/v0_6.rs
crates/types/src/user_operation/v0_7.rs
docs/cli.md

- Implement the PR comments from https://github.com/alchemyplatform/rundler/pull/657

feat: cleanups for entry point v0.7 support

---

crates/sim/src/simulation/simulator.rs
crates/sim/src/simulation/v0_6/context.rs
crates/sim/src/simulation/v0_7/context.rs
crates/sim/tracer/src/validationTracerV0_7.ts

- Went through ERC-7562 and made sure we have coverage for every OP/STO rule that simulation should be catching.

feat(sim): cleanups for v0.7 sim

---

crates/sim/src/simulation/v0_7/context.rs

Closes #665 
- Correctly attribute OP-054 and OP-061 to the correct phase by iterating the call stack

feat(sim): correctly attribute OP-054 and OP-061 to the correct phase

---

crates/builder/src/bundle_proposer.rs
crates/pool/proto/op_pool/op_pool.proto
crates/pool/src/mempool/mod.rs
crates/pool/src/mempool/paymaster.rs
crates/pool/src/mempool/pool.rs
crates/pool/src/mempool/uo_pool.rs
crates/pool/src/server/remote/error.rs
crates/pool/src/server/remote/protos.rs
crates/rpc/src/eth/api.rs
crates/rpc/src/eth/error.rs
crates/sim/src/simulation/context.rs
crates/sim/src/simulation/mod.rs
crates/sim/src/simulation/simulator.rs
crates/sim/src/simulation/unsafe_sim.rs
crates/sim/src/simulation/v0_6/context.rs
crates/sim/src/simulation/v0_7/context.rs
crates/types/src/entity.rs
crates/types/src/pool/error.rs
crates/types/src/pool/types.rs

Closes #660
- Return either the factory or the accessing entity needs to be staked if accessing associated storage during a deploy
- Lots of cleanups to make this easier to express

feat(sim): sto-022 factory or entity needs stake, with cleanups

---

bin/rundler/src/cli/builder.rs
crates/builder/src/bundle_proposer.rs
crates/builder/src/task.rs
docs/cli.md

chore: remove repetitive words

---

crates/builder/src/bundle_sender.rs

- Builder index was missing from a few builder metrics, add it.

fix(builder): add missing builder index to metrics

---

Cargo.lock
bin/rundler/chain_specs/ethereum.toml
bin/rundler/chain_specs/ethereum_sepolia.toml
bin/rundler/src/cli/builder.rs
crates/builder/Cargo.toml
crates/builder/src/lib.rs
crates/builder/src/sender/bloxroute.rs
crates/builder/src/sender/flashbots.rs
crates/builder/src/sender/mod.rs
crates/builder/src/task.rs
crates/types/src/chain.rs
docs/cli.md

feat(builder): support multiple flashbots builders

---

crates/builder/src/bundle_proposer.rs
crates/types/src/user_operation/mod.rs
crates/types/src/user_operation/v0_6.rs
crates/types/src/user_operation/v0_7.rs

fix(types): define entrypoint specific gas overheads

---

.github/scripts/compliance_parser.sh

- Make sure the runner fails if there is no output file from the spec tests

feat(ci): check if output file exists

---

bin/rundler/chain_specs/polygon.toml

- Change the max size of transaction on polygon

feat(tx): change transaction size limit

---

bin/rundler/chain_specs/arbitrum_goerli.toml
bin/rundler/chain_specs/ethereum_goerli.toml
bin/rundler/chain_specs/optimism_goerli.toml
bin/rundler/chain_specs/polygon_mumbai.toml
bin/rundler/src/cli/chain_spec.rs

- Error if the base chain spec has a base key
- Remove goerli hardcoded networks

fix(cli): error if recursive base config, remove goerli netowrks

---

crates/builder/src/bundle_sender.rs
crates/builder/src/transaction_tracker.rs

- Remove dropped status from transaction tracker. No need to track them as we should still increase fees when transactions are dropped, and there are UOs that are willing to pay.
- After increasing fees, if no UOs are willing to pay, then abandon and wait for next trigger
- If replacement underpriced, unabandon to ensure that any transactions are included in the next fee estimation.
The "abandoned" state is used to "retry" after we've reached a point where we can't submit any more UOs. When we get replacement underpriced in this state we'll loop for a few rounds until moving to cancellations. Under normal network conditions, this should only happen if our gas fee estimation is significantly off and transactions are not landing.

fix(builder): improve replacement underpriced handling

---

CODEOWNERS

feat(codeowners): add andy to repo code owners

---

.github/workflows/compliance.yaml

- Fix compliance ci by adding docker-compose to path in action container

feat(compliance): add docker compose to path

---

bin/rundler/src/cli/mod.rs

fix: change bucket range to lower value

---

bin/rundler/src/cli/mod.rs
crates/pool/src/mempool/pool.rs

- Add better bucket distribution for histograms 
- Change TTM metrics to use seconds to fit within histogram distribution

feat(metrics): update histogram buckets and change TTM to seconds

---

crates/provider/src/ethers/metrics_middleware.rs

- Convert duration to milliseconds. Previously the data being spit out was incorrect

feat(metrics): convert to milis

---

Cargo.lock
crates/provider/Cargo.toml
crates/provider/src/alloy/evm.rs

test(evm): add getCodeHash unit test.

---

crates/rpc/src/metrics.rs
crates/task/src/grpc/metrics.rs

- change request latency metrics to milliseconds to fit within the new buckets

feat(funder): change latency metrics to millis

---

crates/builder/src/bundle_sender.rs
crates/builder/src/transaction_tracker.rs

Cherry-pick of https://github.com/alchemyplatform/rundler/pull/811 to `feat/v0.4`

fix(builder): don't forget underpriced info when no ops

---

crates/provider/src/alloy/metrics.rs
crates/rpc/src/rpc_metrics.rs

feat(rpc): log rpc error message.

---

.cargo-husky/hooks/pre-commit
.github/workflows/ci.yaml
Cargo.toml
bin/rundler/Cargo.toml
crates/builder/Cargo.toml
crates/pool/Cargo.toml
crates/provider/Cargo.toml
crates/rpc/Cargo.toml
crates/sim/Cargo.toml
crates/task/Cargo.toml
crates/types/Cargo.toml

style: sort cargo.toml.

---

crates/builder/src/sender/mod.rs

fix: submitter should be used regardless use_submit_for_status's value

---

Cargo.lock
crates/rpc/Cargo.toml
crates/rpc/src/eth/error.rs
crates/sim/Cargo.toml
crates/sim/src/estimation/mod.rs

- rework error message stringify to avoid potential leaking underlying api key. 
-
-

fix: provide better error messages

---

bin/rundler/src/cli/builder.rs
bin/rundler/src/cli/mod.rs
bin/rundler/src/cli/node/mod.rs
bin/rundler/src/cli/pool.rs
bin/rundler/src/cli/rpc.rs
crates/builder/src/bundle_proposer.rs
crates/builder/src/task.rs
crates/pool/src/chain.rs
crates/pool/src/mempool/mod.rs
crates/pool/src/mempool/uo_pool.rs
crates/pool/src/task.rs
crates/provider/src/lib.rs
crates/provider/src/traits/test_utils.rs
crates/rpc/src/task.rs

refactor: use type erasure on types with lots of generics

---

crates/provider/src/alloy/metrics.rs

fix: change provider error log to warning

---

Cross.toml
Dockerfile

- Add prebuild dependencies to cross builder and inject a newer version of libclang to be used with bindgen
- Docs: https://github.com/cross-rs/cross/wiki/FAQ#using-clang--bindgen

feat(libc): upgrade to libc5 in cross builder

---

bin/rundler/chain_specs/opbnb_testnet.toml
bin/rundler/src/cli/chain_spec.rs

fix: amend openbnb testnet config

---

.github/workflows/release.yaml

Related to https://github.com/alchemyplatform/rundler/pull/779

chore(ci): update download-artifact to v4

---

crates/pool/src/chain.rs

- Update the chain tracking logic to use warn

feat(err): use warn instead of debug

---

Cargo.lock
Cargo.toml
Makefile
crates/builder/src/transaction_tracker.rs
crates/pool/Cargo.toml
crates/pool/src/chain.rs
crates/provider/src/alloy/entry_point/mod.rs
crates/rpc/Cargo.toml
crates/rpc/src/eth/api.rs
crates/rpc/src/eth/events/common.rs
crates/rpc/src/eth/events/mod.rs

feat: bump alloy to 0.7.3.

---

crates/builder/src/bundle_sender.rs
crates/builder/src/transaction_tracker.rs

fix: reset metrics when builder re-initialized.

---

crates/builder/src/bundle_sender.rs
crates/builder/src/transaction_tracker.rs

fix: reset metrics when builder re-initialized. (#934)

---

crates/builder/src/bundle_proposer.rs

Fixes #939
- Remove associated ops from mempool when removing an entity from a bundle
- Handle paymaster amendments on entity removal

fix(builder): fix entity removal in bundle building

---

crates/builder/src/bundle_sender.rs
crates/builder/src/transaction_tracker.rs

- Add a metric to track reverted transactions

feat(builder): log and metric for reverted mined bundle transactions

---

crates/sim/src/estimation/v0_6.rs

fix: remove stateoverride for 0.6

---

bin/rundler/chain_specs/ethereum.toml
docs/architecture/rpc.md

This PR fixes the incorrect rpc method in examples.

fix(doc): typos

---

rust-toolchain.toml

chore: add rust toolchain file

---

crates/builder/src/bundle_sender.rs

fix: change revert msg to warn

---

crates/builder/src/bundle_proposer.rs
crates/pool/proto/op_pool/op_pool.proto
crates/pool/src/mempool/uo_pool.rs
crates/pool/src/server/remote/error.rs
crates/rpc/src/eth/error.rs
crates/sim/src/estimation/v0_6.rs
crates/sim/src/estimation/v0_7.rs
crates/sim/src/precheck.rs
crates/types/src/pool/error.rs
crates/types/src/user_operation/mod.rs
crates/types/src/user_operation/v0_6.rs
crates/types/src/user_operation/v0_7.rs

Fixes #954, #955 
- Don't zero out paymaster post op gas limit during gas estimation
- Encorporate paymaster post op gas limit during efficiency check

fix: fix multiple paymaster post op bugs

---

bin/rundler/src/cli/builder.rs
bin/rundler/src/cli/mod.rs
bin/rundler/src/cli/pool.rs
crates/builder/src/bundle_proposer.rs
crates/builder/src/emit.rs
crates/builder/src/task.rs
crates/pool/proto/op_pool/op_pool.proto
crates/pool/src/mempool/mod.rs
crates/pool/src/mempool/uo_pool.rs
crates/pool/src/server/remote/error.rs
crates/rpc/src/eth/error.rs
crates/sim/src/types.rs
crates/types/src/pool/error.rs
docs/cli.md

Closes #924 
- Limit the number of expected storage slots submitted in a bundle
- Block UOs from the mempool that use more than the maximum number of expected storage slots

feat: add maximum number of expected storage slots param

---

funding.json

feat(retro): add funding file

---

crates/types/src/authorization.rs

fix: amend random fix arr_size

---

Cargo.lock
Cargo.toml

feat(0.5.0): update rundler version to 0.5.0

---

crates/pool/src/mempool/pool.rs
crates/pool/src/mempool/uo_pool.rs
crates/types/src/authorization.rs

fix: 7702 validator logic fix (#1004)

---

Cargo.lock
crates/aggregators/pbh/Cargo.toml
crates/aggregators/pbh/src/pbh.rs

Fixes PBH Aggregate signature `PBHPayload` RLP encoding.

fix: pbh signature aggregation rlp encoding

---

crates/builder/src/bundle_proposer.rs
crates/sim/src/lib.rs
crates/sim/src/types.rs

fix(builder): remove expected storage when removing UOs from bundle

---

.github/workflows/docker-release.yaml

feat: only tag `latest` on golden candidate tag

---

Dockerfile

fix(docker): fix docker warnings

---

bin/rundler/src/cli/builder.rs
bin/rundler/src/cli/mod.rs
crates/aggregators/bls/src/bls.rs
crates/aggregators/pbh/src/pbh.rs
crates/aggregators/pbh/src/proxy.rs
crates/builder/src/bundle_proposer.rs
crates/pool/src/mempool/uo_pool.rs
crates/provider/src/alloy/entry_point/v0_6.rs
crates/provider/src/alloy/entry_point/v0_7.rs
crates/provider/src/traits/entry_point.rs
crates/types/src/aggregator.rs

- Process PBH expected entry point reverts in the PBH proxy to remove invalid UOs on bundle simulation

feat(pbh): handle reverts in pbh proxy

---

crates/provider/src/alloy/entry_point/v0_6.rs
crates/provider/src/alloy/entry_point/v0_7.rs
crates/provider/src/traits/evm.rs
crates/sim/src/estimation/estimate_verification_gas.rs

feat: log failed eth call

---

Cargo.lock
bin/rundler/Cargo.toml
bin/rundler/src/cli/mod.rs
bin/rundler/src/cli/tracing.rs
crates/rpc/src/eth/router.rs
crates/rpc/src/eth/server.rs
crates/rpc/src/rundler.rs
crates/sim/src/gas/gas.rs
docs/cli.md

- Add OTLP tracing layer to send spans
- Add `LOG_OTLP_GRPC_ENDPOINT` environment variable
- Instrument a basic span

feat: add otlp tracing

---

bin/rundler/src/cli/mod.rs
bin/rundler/src/cli/tracing.rs

- pass network attribute to traces

feat: add network attribute to otlp traces

---

Cargo.lock
bin/rundler/Cargo.toml
bin/rundler/src/cli/mod.rs
bin/rundler/src/cli/tracing.rs
crates/pool/src/chain.rs
crates/pool/src/mempool/paymaster.rs
crates/pool/src/mempool/uo_pool.rs
crates/provider/src/alloy/da/arbitrum.rs
crates/provider/src/alloy/da/local/bedrock.rs
crates/provider/src/alloy/da/local/nitro.rs
crates/provider/src/alloy/da/optimism.rs
crates/provider/src/alloy/entry_point/v0_6.rs
crates/provider/src/alloy/entry_point/v0_7.rs
crates/provider/src/alloy/evm.rs
crates/rpc/src/eth/api.rs
crates/rpc/src/eth/events/common.rs
crates/rpc/src/eth/events/mod.rs
crates/rpc/src/eth/router.rs
crates/rpc/src/eth/server.rs
crates/rpc/src/rundler.rs
crates/sim/src/estimation/estimate_call_gas.rs
crates/sim/src/estimation/estimate_verification_gas.rs
crates/sim/src/estimation/v0_6.rs
crates/sim/src/estimation/v0_7.rs
crates/sim/src/gas/gas.rs
crates/sim/src/gas/oracle.rs
crates/sim/src/precheck.rs
docs/cli.md

feat: merge otlp instrument

---

crates/pool/src/chain.rs
crates/pool/src/mempool/paymaster.rs
crates/pool/src/mempool/uo_pool.rs
crates/provider/src/alloy/da/arbitrum.rs
crates/provider/src/alloy/da/local/bedrock.rs
crates/provider/src/alloy/da/local/nitro.rs
crates/provider/src/alloy/da/optimism.rs
crates/provider/src/alloy/entry_point/v0_6.rs
crates/provider/src/alloy/entry_point/v0_7.rs
crates/provider/src/alloy/evm.rs
crates/rpc/src/eth/api.rs
crates/rpc/src/eth/events/common.rs
crates/rpc/src/eth/events/mod.rs
crates/rpc/src/eth/server.rs
crates/rpc/src/rundler.rs
crates/sim/src/estimation/estimate_call_gas.rs
crates/sim/src/estimation/v0_6.rs
crates/sim/src/gas/gas.rs
crates/sim/src/gas/oracle.rs
crates/sim/src/precheck.rs

fix: otlp ignore most arguments

---

crates/rpc/src/eth/server.rs
crates/rpc/src/rundler.rs

feat: add rpc_method to root span

---

crates/builder/src/bundle_proposer.rs
crates/builder/src/emit.rs
crates/builder/src/task.rs
crates/builder/src/transaction_tracker.rs

Main PR: https://github.com/alchemyplatform/rundler/pull/1062

fix(builder): fix tracker tag, abandon metrics, rejected by time log

---

Cargo.lock
crates/builder/src/bundle_proposer.rs
crates/builder/src/emit.rs
crates/pool/proto/op_pool/op_pool.proto
crates/pool/src/mempool/pool.rs
crates/pool/src/server/remote/protos.rs
crates/pool/src/server/remote/server.rs
crates/rpc/src/eth/api.rs
crates/rpc/src/types/permissions.rs
crates/sim/src/precheck.rs
crates/types/src/gas.rs
crates/types/src/timestamp.rs
crates/types/src/user_operation/mod.rs
crates/types/src/user_operation/permissions.rs
docs/architecture/rpc.md

- Add a bundler sponsorship permission
- This permission enforces that the bundler pays all of the gas for the user operation, up to a max cost and in a time range
- Time range is best effort as its not enforced onchain.
TODO:

feat: implement bundler sponsorship

---

Cargo.lock
bin/rundler/src/cli/admin/defund_signers.rs
bin/rundler/src/cli/admin/fund_signers.rs
bin/rundler/src/cli/builder.rs
bin/rundler/src/cli/signer.rs
crates/signer/Cargo.toml
crates/signer/src/aws.rs
crates/signer/src/funding.rs
crates/signer/src/lib.rs
crates/signer/src/manager.rs

feat(signer): update how signer is configured from cli

---

crates/pool/src/mempool/pool.rs

feat: track total 7702 uos

---

.github/workflows/release.yaml

https://github.com/actions/runner-images/issues/11101

chore(ci): update ubuntu runner in release

---

crates/builder/src/bundle_proposer.rs

fix(bulder): add a buffer to the max bundle fee limit in bundle proposer

---

Cargo.lock
crates/builder/src/bundle_proposer.rs
crates/sim/Cargo.toml
crates/sim/src/estimation/mod.rs
crates/sim/src/estimation/v0_6.rs
crates/sim/src/estimation/v0_7.rs

- Add more metrics measuring latency for hot-path remote calls/functions

feat: add more latency metrics

---

crates/rpc/src/eth/events/common.rs
crates/rpc/src/eth/events/mod.rs
crates/rpc/src/eth/events/v0_6.rs
crates/rpc/src/eth/events/v0_7.rs

fix(rpc): fix uo receipt log indexing

---

bin/rundler/chain_specs/base_sepolia.toml
bin/rundler/chain_specs/ethereum_sepolia.toml
bin/rundler/chain_specs/optimism_sepolia.toml
bin/rundler/src/cli/builder.rs
bin/rundler/src/cli/mod.rs
bin/rundler/src/cli/pool.rs
crates/builder/src/bundle_proposer.rs
crates/builder/src/task.rs
crates/pool/proto/op_pool/op_pool.proto
crates/pool/src/mempool/mod.rs
crates/pool/src/mempool/pool.rs
crates/pool/src/mempool/uo_pool.rs
crates/sim/src/estimation/mod.rs
crates/sim/src/estimation/v0_6.rs
crates/sim/src/estimation/v0_7.rs
crates/sim/src/gas.rs
crates/sim/src/precheck.rs
crates/types/src/chain.rs
crates/types/src/pool/error.rs
crates/types/src/user_operation/mod.rs
crates/types/src/user_operation/v0_6.rs
crates/types/src/user_operation/v0_7.rs
docs/architecture/README.md
docs/architecture/eip7623.md
docs/cli.md

- Handling for https://eips.ethereum.org/EIPS/eip-7623
- Account for required floor during bundle gas estimation
- Account for new gas used during required pvg calc and estimation
- Split verification and execution gas limit efficiency threshold configs

feat: add handling for eip-7623 in builder and pvg calc

---

bin/rundler/chain_specs/arbitrum_sepolia.toml
bin/rundler/chain_specs/base.toml
bin/rundler/chain_specs/ethereum.toml
bin/rundler/chain_specs/optimism.toml
bin/rundler/src/cli/pool.rs
crates/pool/src/mempool/mod.rs
crates/pool/src/mempool/pool.rs
crates/pool/src/mempool/uo_pool.rs
crates/rpc/src/eth/api.rs
crates/types/src/chain.rs
crates/types/src/user_operation/mod.rs

Closes #1072 
- Return an error in gas estimation when EIP-7702 is not supported

feat(rpc): improve error msg when 7702 is not supported

---

crates/pool/proto/op_pool/op_pool.proto
crates/pool/src/mempool/pool.rs
crates/pool/src/server/remote/error.rs
crates/rpc/src/eth/error.rs
crates/types/src/pool/error.rs

- Catch error that is currently mapped into an internal error

feat(errors): catch error and map to invalid params

---

crates/types/src/chain.rs

Closes #1149 
- Adds `chain.eip7623_enabled` so that users can configure the default settings for the EIP.

feat: add chain.eip7623_enabled config

---

crates/rpc/src/rundler.rs
crates/rpc/src/types/mod.rs
docs/architecture/rpc.md

Closes #1148 
- Adds `rundler_getUserOperationStatus`. See `rpc.md` for details

feat(rpc): add rundler_getUserOperationStatus

---

crates/sim/src/estimation/estimate_call_gas.rs
crates/sim/src/estimation/estimate_verification_gas.rs
crates/sim/src/estimation/mod.rs
crates/sim/src/estimation/v0_6.rs
crates/sim/src/estimation/v0_7.rs

- Return the decoded validation error during estimation as opposed to the opaque bytes

fix(sim): return decoded validation errors during estimation

---

crates/sim/tracer/src/validationTracerV0_6.ts

- Associate forbidden opcodes with the top level entity that called it, not the contract that it was called by

fix(sim): fix v0.6 tracer opcode contract association

---

crates/builder/src/server/local.rs
crates/pool/src/server/local.rs

feat: add metric to measure channel dealy

---

Cross.toml

chore(docker): add ca certs to cross docker container

---

crates/rpc/src/rundler.rs

fix: make rpc name consist with tracer span

---

crates/pool/src/server/local.rs

fix: ignore preconfirmed node for new chain header

---

crates/types/src/tag.rs

fix: allow both upper case and lower case tag

---

crates/pool/src/chain.rs
crates/task/src/block_watcher.rs

fix: flashblock will not retry
