alchemyplatform/rundler

crates/builder/Cargo.toml, crates/builder/src/bundle_proposer.rs, crates/sim/src/gas/gas.rs, crates/sim/src/precheck.rs
#349
- Only count the 21000 transaction gas cost once in the entire bundle
=> fix(gas): amortize evm transaction fixed cost over bundle

crates/sim/src/gas/gas.rs
Contributes to #349
Improve the bundle gas limit calculation. The bundle gas limit we now use is based off the following observation:
In the Entrypoint contract, the `innerHandleOp` call has [this check](https://github.com/eth-infinitism/account-abstraction/blob/da5d2d50853b8dca47bdca49337d26d1333a08a3/contracts/core/EntryPoint.sol#L264) that the bundle would need to pass for every single user op that it executes. 
Within a bundle, let $p_i$, $v_i$, and $c_i$ be the static pre-verification gas, verification gas limit, and call gas limit of user operation $i$. Also let $m_i$ be $1$ if user op $i$ uses a paymaster, and $0$ if not. Suppose we start with initial gas $g$. When processing user op $i$, at the point of the the `innerHandleOp` check we have yet to execute the call for user op $i$, …
=> fix(gas): improve bundle gas estimation calculation

.github/workflows/compliance.yaml, Cargo.lock, crates/builder/proto/builder/builder.proto, crates/builder/src/bundle_sender.rs, crates/builder/src/server/local.rs, crates/builder/src/server/mod.rs, crates/builder/src/server/remote/client.rs, crates/builder/src/server/remote/server.rs, crates/builder/src/task.rs, crates/builder/src/transaction_tracker.rs, crates/pool/src/server/mod.rs, crates/rpc/Cargo.toml, crates/rpc/src/debug.rs, test/spec-tests/ci/run-spec-tests.sh, test/spec-tests/launchers/rundler-launcher/docker-compose.yml, test/spec-tests/launchers/rundler-launcher/rundler-launcher.sh, test/spec-tests/launchers/rundler-launcher/waitForServices.sh
Closes #147
- Add spec tests to CI and fix timeout issues due to race condition
- Update `debug_sendBundleNow` so that we wait for the pool to be updated to the same transaction block before returning
=> feat(spectests): fix timeout and run in CI

crates/builder/src/bundle_sender.rs, crates/builder/src/transaction_tracker.rs
Closes #379 
- Log gas limit, gas used, and gas limit utilization for mined bundles
=> feat(builder): add bundle gas stats to metrics

crates/builder/src/bundle_proposer.rs, crates/sim/src/gas/gas.rs, crates/sim/src/gas/polygon.rs, crates/sim/src/precheck.rs
#349
Add a two phase bundle gas filtering process. In the first phase, we filter the UOs in the pool down to a subset that we want to simulate. This phase intentionally includes more UOs than necessary in order to account for any UOs that might be dropped later on. The second phase of filtering happens after simulation. At this point we are able to get a better gas limit estimate for each UO because we know for sure if the UO uses a `postOp` or not, and also drop UOs that fail validation. This filtering is when we ensure that all the UOs we have selected satisfy the maximum bundle gas limit.
=> feat(builder): add two phase UO gas limit filtering

crates/builder/src/bundle_proposer.rs, crates/sim/src/gas/gas.rs, crates/sim/src/gas/polygon.rs, crates/sim/src/precheck.rs, crates/sim/src/simulation/simulation.rs
#349
- In the gas limit calculation, only multiply the verification gas limit by 3 if we know the user operation uses a paymaster that has a postOp
=> feat(builder): only include paymaster gas if there is a postOp

Dockerfile
I was looking into the cargo chef build speeds in CI and found a few interesting things that have been implemented and recommended by the chef project.
this was first proposed in https://github.com/LukeMathWalker/cargo-chef/issues/180 and eventually zcach found a workaround with rzync in the following PR https://github.com/ZcashFoundation/zebra/pull/6934
=> chore(docker): do not overide cache with COPY

Cargo.lock, bin/rundler/Cargo.toml, bin/rundler/src/cli/tracing.rs
- Some dependencies we rely on use the `log` create, we should capture those logs to our tracing subscriber
=> feat(log): capture logs from the log crate to tracing subscriber

crates/builder/src/signer/aws.rs
Closes #361
- Change create conditional signer based on length of kms keys so that the kms_guard can be turned into an optional field and not created with only one key id
=> feat(kms): do not require distributed locking when only using one kms key

docs/architecture/builder.md, docs/architecture/pool.md, docs/architecture/rpc.md, docs/proto.md
=> chore: fix typos

bin/rundler/src/cli/mod.rs, bin/rundler/src/cli/pool.rs, crates/pool/src/mempool/mod.rs, crates/pool/src/mempool/pool.rs, crates/pool/src/mempool/uo_pool.rs
Fixes #450 
- add constants related to throttling and update throttling logic to use the constants
=> feat(pool): update throttling logic

crates/pool/src/chain.rs, crates/pool/src/mempool/pool.rs, crates/pool/src/mempool/uo_pool.rs, crates/types/src/user_operation.rs
Closes #278 
- Use the useroperation id to get the hash instead so we can make sure we are removing the correct item from the hashmap
=> feat(mempool): check for same nonce and sender 

bin/rundler/src/cli/mod.rs, crates/sim/src/precheck.rs, crates/types/src/chain.rs, docs/cli.md
Closes #405 
- Add and use a `fee_accept_percent` configuration to the prechecker that allows user operations into the mempool that bid a minimum of X% of the current bundle fees.
=> feat: add config for fee accept percentage

crates/builder/src/bundle_proposer.rs, crates/provider/src/ethers/entry_point.rs, crates/provider/src/traits/entry_point.rs
Handle the bug in the 0.6 entry point that was fixed here https://github.com/eth-infinitism/account-abstraction/pull/325
=> fix(builder): handle the post op revert 0.6 entry point bug

crates/builder/src/bundle_proposer.rs
- Do not send to the pool an entity update when an revert is due to an invalid nonce since it can occur without a sender acting maliciously
=> fix(builder): do not send entity update for reverts due to invalid nonce

.github/workflows/ci.yaml, Cargo.toml, Dockerfile, bin/rundler/src/cli/builder.rs, bin/rundler/src/cli/node/mod.rs, bin/rundler/src/cli/pool.rs, crates/sim/src/simulation/simulation.rs
- Update Rust to 1.75
- Fix lints
=> chore: update to rust 1.75

crates/builder/src/bundle_sender.rs, crates/builder/src/sender/bloxroute.rs, crates/builder/src/sender/conditional.rs, crates/builder/src/sender/flashbots.rs, crates/builder/src/sender/mod.rs, crates/builder/src/sender/raw.rs, crates/builder/src/transaction_tracker.rs, crates/types/src/gas.rs, crates/utils/src/math.rs
Applies to #550 
- Retry bundle transactions if we receive `replacement transaction underpriced`
=> fix(builder): try underpriced bundle txns again

crates/pool/src/chain.rs, crates/pool/src/emit.rs, crates/pool/src/mempool/pool.rs, crates/pool/src/mempool/uo_pool.rs
Closes #502 
Evict UOs once the last mined block's timestamp has passed their valid_until field
=> feat(pool): remove expired UOs from pool each block

Cargo.lock, crates/pool/proto/op_pool/op_pool.proto, crates/pool/src/mempool/mod.rs, crates/pool/src/mempool/uo_pool.rs, crates/pool/src/server/local.rs, crates/pool/src/server/mod.rs, crates/pool/src/server/remote/client.rs, crates/pool/src/server/remote/mod.rs, crates/pool/src/server/remote/protos.rs, crates/pool/src/server/remote/server.rs, crates/rpc/Cargo.toml, crates/rpc/src/eth/api.rs, crates/rpc/src/types.rs
Closes #529 
- Add endpoint to pool to get a pending user operation by hash
- Use that endpoint in `eth_getUserOperationByHash` to return pending UOs
=> feat(rpc): include pending UOs in eth_getUserOperationByHash

crates/builder/src/bundle_proposer.rs, crates/pool/src/mempool/uo_pool.rs, crates/sim/src/lib.rs, crates/sim/src/simulation/mempool.rs, crates/sim/src/simulation/mod.rs, crates/sim/src/simulation/simulation.rs
Fixes #354
- Mark allowlisted unstaked entities as staked
=> feat(sim): allow mempool configs to modify simulation results

bin/rundler/src/cli/mod.rs, crates/provider/src/ethers/provider.rs, crates/provider/src/traits/provider.rs, crates/rpc/src/eth/api.rs, crates/rpc/src/eth/error.rs, crates/rpc/src/eth/mod.rs, crates/rpc/src/eth/server.rs, crates/sim/src/estimation/estimation.rs, crates/sim/src/estimation/types.rs, crates/sim/src/simulation/simulation.rs, crates/sim/src/utils.rs, docs/architecture/rpc.md, docs/cli.md
Closes #525
Closes #530
- Add state overrides to `eth_estimateUserOperationGas`
- Move revert bytes to `revert_bytes` in the data field of the `eth_estimateUserOperationGas` error response
=> feat(rpc): add state overrides to estimate gas, fix error msg

Cargo.lock, bin/rundler/src/cli/pool.rs, crates/pool/proto/op_pool/op_pool.proto, crates/pool/src/mempool/error.rs, crates/pool/src/mempool/mod.rs, crates/pool/src/mempool/pool.rs, crates/pool/src/mempool/reputation.rs, crates/pool/src/mempool/uo_pool.rs, crates/pool/src/server/remote/error.rs, crates/sim/Cargo.toml, crates/sim/src/simulation/simulation.rs, docs/cli.md
Closes #454, closes #354
- Track reputation of all entities
- Move `SAME_SENDER_MEMPOOL_COUNT` check out from `PoolInner` into `UoPool`
- Do UREP-020 check in the same pool read lock as `SAME_SENDER_MEMPOOL_COUNT` check
- Fix bug where we increment instead of decrement the reputation of an entity for an unmined transaction
=> feat(pool): handle UREP-020 and track reputation of unstaked entities

crates/pool/proto/op_pool/op_pool.proto, crates/pool/src/mempool/mod.rs, crates/pool/src/mempool/reputation.rs, crates/pool/src/mempool/uo_pool.rs, crates/pool/src/server/local.rs, crates/pool/src/server/mod.rs, crates/pool/src/server/remote/client.rs, crates/pool/src/server/remote/server.rs, crates/rpc/src/debug.rs
- Add the `debug_bundler_clearMempool` RPC method which is used in the spec test: https://github.com/alchemyplatform/bundler-spec-tests/blob/12bf62752d4af78ed383e6ec4c1a610ebaea1787/tests/utils.py#L184. The spec test uses the method to clear the mempool but not the reputations, which is why we need a different endpoint than `debug_bundler_clearState`
=> feat(rpc): add debug_bundler_clearMempool endpoint

crates/sim/src/estimation/estimation.rs
=> fix: clarify simulateHandleOp error can be caused by contract deployment

Cargo.lock, Cargo.toml, bin/rundler/Cargo.toml, bin/rundler/src/cli/pool.rs, crates/builder/Cargo.toml, crates/builder/src/sender/mod.rs, crates/sim/Cargo.toml, crates/sim/src/estimation/estimation.rs, crates/sim/src/gas/gas.rs, crates/sim/src/precheck.rs, crates/types/Cargo.toml, crates/types/src/chain.rs
Add polygon amoy and use alloy-rs for chain definitions
=> feat(chains): add polygon amoy and use alloy-rs

crates/pool/proto/op_pool/op_pool.proto, crates/pool/src/server/remote/error.rs, crates/rpc/src/eth/error.rs, crates/sim/src/estimation/estimation.rs, crates/sim/src/simulation/mod.rs, crates/sim/src/simulation/simulation.rs
Closes #593 
- Adds a simulation violation check that requires a UO to have at least a 2000 gas buffer on their `verificationGasLimit` compared to what is used during simulation. This accounts for a situation where a UO can use slightly more than their VGL onchain, causing a bundle to revert.
=> feat(sim): reject UOs that don't have a buffer on verification gas limit

bin/rundler/chain_specs/dev.toml, crates/builder/src/bundle_sender.rs, crates/builder/src/server/local.rs, crates/builder/src/task.rs, crates/types/src/chain.rs
Closes #598
- Adds a timer based trigger to the bundle sender. The bundle sender will send a bundle if the timer elapses before it receives the next block. Currently this is set to maximum time for all networks except for dev where it is set to 250ms. This allows bundles to be sent on dev Geth where blocks are only triggered when transactions arrive.
- Its possible there will be other networks that have unpredictable block times where this chain spec rule could be useful.
- Fixes switching between bundling modes. Previously if we transition to manual mode we'd never be able to exit unless the tests switch the mode while bundling building is in flight. Once we looped back around we'd be stuck in manual mode until a new bundle was triggered. Doing this required a refactor of how the server …
=> feat(builder): add a timer based trigger to bundle building

.github/workflows/docker-release.yaml, .github/workflows/release.yaml, Cargo.lock, Cargo.toml, Cross.toml, Dockerfile, Dockerfile.build, Makefile, bin/rundler/Cargo.toml, deny.toml
Fixes for release pipeline to test workflows
=> feat(release): update version

docs/docker.md
This adds the missing command parameter to the example docker-compose config, without this `docker-compose up` will not run as rundler needs a command specified
=> fix(docs): add missing command to full node docker-compose.yaml example

crates/sim/src/estimation/estimation.rs, crates/types/src/chain.rs
- The new fix gas cost logic in estimation misses an edge case where the balance is enough to cover the cost during estimation, but not enough to cover the cost onchain. To handle this, always add a static buffer to cover.
=> fix(sim): account for native transfer overhead in estimation

bin/rundler/src/cli/mod.rs, crates/rpc/src/eth/api.rs, crates/sim/src/estimation/estimation.rs, crates/sim/src/estimation/types.rs, crates/types/src/chain.rs, docs/architecture/rpc.md, docs/cli.md
- See the docs for a description of the proposed change.
- TLDR: using zero fees during the no paymaster verification estimation case. In the paymaster case we use the constant.
- Changes the name of the constant to be more consistent.
=> feat(rpc): use zero fees in no paymaster estimation case

bin/rundler/src/cli/builder.rs, bin/rundler/src/cli/mod.rs, bin/rundler/src/cli/pool.rs, bin/rundler/src/cli/rpc.rs, crates/builder/src/task.rs, crates/pool/src/task.rs, crates/provider/src/ethers/entry_point/v0_6.rs, crates/provider/src/ethers/entry_point/v0_7.rs, crates/provider/src/traits/entry_point.rs, crates/provider/src/traits/test_utils.rs, crates/rpc/src/eth/router.rs, crates/rpc/src/task.rs, crates/sim/src/simulation/v0_6/mod.rs, crates/sim/src/simulation/v0_6/simulator.rs, crates/sim/src/simulation/v0_6/unsafe_sim.rs
Closes #470 
- Add unsafe mode for EP v0.6
=> feat: unsafe mode for EP v0.6

bin/rundler/src/cli/builder.rs, bin/rundler/src/cli/pool.rs, crates/sim/src/simulation/mempool.rs
Correctly deserialize the `entryPoint` field, and display a more descriptive error when deserialization fails.
=> fix(mempool): fix configuration deserialization

crates/builder/src/task.rs, crates/pool/src/task.rs, crates/sim/src/simulation/context.rs, crates/sim/src/simulation/mod.rs, crates/sim/src/simulation/simulator.rs, crates/sim/src/simulation/v0_6/context.rs, crates/sim/src/simulation/v0_6/mod.rs, crates/sim/src/simulation/v0_6/tracer.rs, crates/types/src/validation_results.rs
- Refactor tracing and context providing from simulation
- Introduce a `ValidationContextProvider` trait.
- This trait can be implemented for both v0.6 and v0.7 to surface all of the tracing information needed to compile the simulation violations.
- The `ValidationContext` result is likely to change when v0.7 is implemented, but wanted to do this refactor first to limit the diff.
- The trait also exposes a `get_specific_violations` function for any entry point specific logic (likely only to be used for v0.6)
=> refactor: create context interface for simulation

crates/sim/src/estimation/v0_7.rs, crates/sim/src/simulation/v0_7/context.rs, crates/sim/src/types.rs, crates/types/src/validation_results.rs
- A previous change moved this erroneously to U256 for v0.7, move it back and provide a simple insert function.
=> fix(sim): use H256 instead of U256 for expected storage

crates/sim/src/simulation/v0_7/context.rs, crates/sim/src/simulation/v0_7/tracer.rs, crates/sim/tracer/src/validationTracerV0_7.ts
- The reference tracer tracks reads/writes within top level calls, not globally. This led to bugs when the factory would write to some slot and then the account would read it (i.e. a deploy). Our existing approach would capture the account read as an expected slot, and fail to send the bundle.
- The fix uses the same approach from the v0.6 tracer to capture global accesses, only returning slots that were first read.
=> fix(sim): use same method for expected storage in v0.7 from v0.6 tracer

crates/rpc/src/types/mod.rs, crates/sim/src/estimation/v0_6.rs, crates/sim/src/estimation/v0_7.rs, crates/types/src/user_operation/mod.rs
We don't have a reasonable way to compute these and they are soon getting removed in an update to ERC-4337.
=> chore(simulation): remove postop gas estimates

crates/pool/proto/op_pool/op_pool.proto, crates/pool/src/server/remote/error.rs, crates/provider/src/ethers/entry_point/v0_6.rs, crates/provider/src/ethers/entry_point/v0_7.rs, crates/provider/src/traits/entry_point.rs, crates/provider/src/traits/test_utils.rs, crates/rpc/src/eth/error.rs, crates/sim/src/estimation/estimate_verification_gas.rs, crates/sim/src/estimation/mod.rs, crates/sim/src/estimation/v0_6.rs, crates/sim/src/simulation/v0_7/context.rs, crates/types/src/validation_results.rs
When validation fails in 0.7 in either simulation or gas estimation, the entry point now surfaces the inner revert which caused validation to fail. Surface this in the error response in the rpc, using the `data` field to return an object with the fields:
- `entry_point_reason`: the entry point string like "AA99 some failure". This is the only field populated in v0.6.
- `inner_revert_bytes`: the raw bytes of the inner revert message.
- `inner_revert_reason`: if the inner revert is caused by a Solidity `require` or `assert`, then the string message provided to it.
=> feat(rpc): return validation revert data from rpc

crates/rpc/src/eth/error.rs, crates/sim/src/estimation/estimate_call_gas.rs, crates/sim/src/estimation/mod.rs, crates/sim/src/estimation/v0_6.rs, crates/sim/src/estimation/v0_7.rs, crates/sim/src/precheck.rs, crates/types/contracts/src/utils/CallGasEstimationProxy.sol, crates/types/src/user_operation/mod.rs, crates/types/src/user_operation/v0_6.rs, crates/types/src/user_operation/v0_7.rs
=> feat(sim): skip estimation if gas field is provided in op

crates/rpc/src/eth/router.rs, crates/rpc/src/types/mod.rs, crates/rpc/src/types/v0_6.rs, crates/rpc/src/types/v0_7.rs
- Add types for v0.6 and v0.7 gas estimation and only return relevant fields.
=> feat(rpc): add distinct types for EP version gas estimations

crates/rpc/src/admin.rs, crates/rpc/src/debug.rs, crates/rpc/src/eth/mod.rs, crates/rpc/src/eth/server.rs, crates/rpc/src/lib.rs, crates/rpc/src/rundler.rs, crates/rpc/src/utils.rs
- Previously panics would just drop the connection and silently occur
- New behavior is to catch them, return an internal error, and increment a metric that can be alerted upon
=> feat(rpc): return internal errors and increment metric on panic

bin/rundler/src/cli/builder.rs, docs/cli.md
- On startup check that the configured number of keys is greater than or equal to the total number of builders across the two entrypoints.
=> fix(cli): enforce num keys greater than or equal to num builders

bin/rundler/chain_specs/arbitrum.toml, bin/rundler/chain_specs/base.toml, bin/rundler/chain_specs/optimism.toml, bin/rundler/chain_specs/polygon.toml, crates/builder/src/bundle_proposer.rs, crates/provider/src/ethers/provider.rs, crates/provider/src/traits/provider.rs, crates/rpc/src/eth/api.rs, crates/rpc/src/task.rs, crates/sim/src/estimation/estimate_verification_gas.rs, crates/sim/src/estimation/v0_6.rs, crates/sim/src/utils.rs, crates/types/contracts/src/utils/GetGasUsed.sol, crates/types/src/chain.rs, crates/types/src/user_operation/mod.rs, crates/types/src/user_operation/v0_6.rs, crates/types/src/user_operation/v0_7.rs, docs/architecture/builder.md, docs/architecture/pool.md, docs/architecture/rpc.md
- Old code used the constructor revert method to check gas used. This ran into the limitation that Geth limits the initCode supplied on contract creation to 48 KiB which is less than what it uses for its transaction limit, 128 KiB.
- New code uses state overrides instead, which is the preferred method as it makes the contracts easier to reason about.
- Added a check at the RPC layer for UO size
- Added a setting to the RPC server for max body size as max transaction size * 2
=> fix(provider): use state overrides for gas used, not ctor method

crates/builder/src/bundle_proposer.rs
- Filter UOs by fee before applying the bundle gas limit 
- Before, if there are a lot of underpriced UOs (specifically by base fee or PVG, as they're sorted by priority fee) then they'll block correctly priced UOs from making it to the simulation stage.
- Now, we filter by fee prior to filtering by gas limit. It does add an extra async step, but will improve when we're doing gas limiting.
=> fix(builder): filter fee before filtering by gas limit

Cargo.lock, crates/builder/src/bundle_proposer.rs, crates/pool/src/server/remote/error.rs, crates/rpc/src/eth/error.rs, crates/sim/src/simulation/context.rs, crates/sim/src/simulation/mempool.rs, crates/sim/src/simulation/simulator.rs, crates/sim/src/simulation/v0_7/context.rs, crates/sim/src/simulation/v0_7/tracer.rs, crates/sim/tracer/src/validationTracerV0_6.ts, crates/types/Cargo.toml, crates/types/src/lib.rs, crates/types/src/opcode.rs, test/spec-tests/local/docker-compose.yml, test/spec-tests/local/launcher.sh, test/spec-tests/remote/docker-compose.yml, test/spec-tests/remote/launcher.sh
- Add a new Opcode class, copied from ethers-rs but adds new opcodes (can remove if PR accepted next release)
- Update geth in testing to 1.14
=> fix(sim): update simulation for dencun opcodes

crates/builder/src/bundle_proposer.rs, crates/pool/proto/op_pool/op_pool.proto, crates/pool/src/server/remote/error.rs, crates/sim/src/simulation/simulator.rs, crates/types/src/pool/error.rs, crates/types/src/user_operation/mod.rs, crates/types/src/validation_results.rs, docs/architecture/pool.md
- Add check during simulation for a valid time range and add a 15 second buffer
=> feat(simulation): check whether the op fits within a valid time range

crates/sim/src/estimation/estimate_call_gas.rs, crates/sim/src/estimation/v0_6.rs, crates/sim/src/estimation/v0_7.rs, crates/types/build.rs, crates/types/contracts/src/utils/CallGasEstimationProxyTypes.sol, crates/types/contracts/src/v0_6/CallGasEstimationProxy.sol, crates/types/contracts/src/v0_7/CallGasEstimationProxy.sol
- Handle the special call for `executeUserOp` during gas estimation.
- This required modifications to the call gas proxy that are v0.7 specific.
- Update the call gas specializations code to handle multiple proxy implementations.
=> fix(sim): handle v0.7 executeUserOp special call in call gas estimation

Cargo.lock, bin/rundler/Cargo.toml, bin/rundler/src/cli/builder.rs, bin/rundler/src/cli/mod.rs, bin/rundler/src/cli/pool.rs, crates/builder/src/task.rs, crates/pool/src/task.rs, crates/sim/src/simulation/context.rs, crates/sim/src/simulation/mod.rs, crates/sim/src/simulation/simulator.rs, crates/sim/src/simulation/v0_6/context.rs, crates/sim/src/simulation/v0_6/tracer.rs, crates/sim/src/simulation/v0_7/context.rs, crates/sim/src/simulation/v0_7/tracer.rs, docs/cli.md
- Change timeout of debug_traceCall for custom tracers to 10s instead of the default 5s
- Add CLI flag to make it customizable 
DOCS: 
https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug
https://pkg.go.dev/time#ParseDuration
=> feat(tracer): add timeout of 10s to tracer

crates/builder/src/bundle_sender.rs, crates/builder/src/server/local.rs
- Refactor state machine
- Refactor metrics by saving an object with common components
=> refactor(builder): large refactor of bundle sender state machine and metrics

crates/pool/src/mempool/paymaster.rs, crates/pool/src/mempool/uo_pool.rs, crates/rpc/src/eth/error.rs
- Fix race condition
Race
1. Paymaster sends deposit transaction
2. UO uses paymaster, paymaster is new to the pool, queries chain for balance and adds to cache, sees the balance from 1
3. Deposit event from (1) is notified to the pool, balance is added to the balance from (2)
Since there is no ordering guarantee between (2) and (3) you can end up with either balance or 2x balance in the cache.
Instead process events as a reset event, and just query the chain for a balance after an event.
=> fix(pool): fix race condition in paymaster tracking

crates/builder/src/bundle_proposer.rs, crates/builder/src/bundle_sender.rs, crates/builder/src/sender/bloxroute.rs, crates/builder/src/sender/conditional.rs, crates/builder/src/sender/flashbots.rs, crates/builder/src/sender/mod.rs, crates/builder/src/sender/raw.rs, crates/builder/src/server/local.rs, crates/builder/src/transaction_tracker.rs
Closes #550 
- Define bundle abandonment as - there is a pending bundle but after fee increases there are no longer any high enough paying UOs to increase the fees.
- Modify sender state machine to funnel every bundle abandonment to the same state - "replacement underpriced." That is, when a bundle is abandoned clear the transaction tracker and start from scratch. On networks where the previous txn may still be in the mempool, we will get a "replacement underpriced." On other networks, starting from scratch allows us to continue.
- Handle "replacement underpriced" errors with cancellations.
- For the flashbots sender, use a "soft cancellation", which is just an API call and doesn't require polling
- For all other senders, use a "hard cancellation", which requires a transaction to be sent …
=> feat(builder): cancel transaction when replacement underpriced

crates/pool/src/mempool/pool.rs, crates/pool/src/mempool/uo_pool.rs
Closes #319
- Add time to mine context to user operations in the pool
- Track the number of user operations that are currently "candidates" i.e. their fees are high enough to be included
- Track the amount of time/blocks an operation spends in the "candidate" state
- Add histogram for time/blocks to mine
- Re-use the expiry loop into a maintenance loop to limit O(n) operations
- Limitation: time to mine has a granularity of 1(s) so on fast block networks (Arbitrum) we don't have the level of granularity needed, however we do have N blocks.
- Open question: should we switch candidate time to be based on system time and not block time?
=> feat(pool): add time to mine tracking and metrics

crates/pool/src/mempool/uo_pool.rs, test/spec-tests/local/launcher.sh
Original: https://github.com/alchemyplatform/rundler/pull/726
=> feat(pool): allow staked senders to have multiple UOs in best_operations

bin/rundler/src/cli/mod.rs
- Set back to 10s after testing 15s localy
=> fix(tracer): set tracer timeout default back to 10s

bin/rundler/src/cli/builder.rs, crates/builder/src/task.rs, docs/cli.md
Closes #724 
- Add `builder.private_keys` CLI flag. Deprecate `builder.private_key`, combine if both used.
- Consume multiple private keys when creating bundle builders
=> feat(builder): allow for multiple private keys

crates/builder/src/bundle_proposer.rs, crates/builder/src/bundle_sender.rs, crates/builder/src/transaction_tracker.rs
Create a unit testing framework for bundle_sender and write some tests.
=> chore(builder): add unit tests to bundle_sender

bin/rundler/src/cli/builder.rs, crates/builder/src/bundle_proposer.rs, crates/builder/src/bundle_sender.rs, crates/builder/src/task.rs, crates/builder/src/transaction_tracker.rs, crates/pool/src/mempool/pool.rs, docs/architecture/builder.md, docs/cli.md
Implement a better tracking mechanism for state machine replacement underpriced tracking.
TODO:
=> fix(builder): fix builder state machine replacement tracking

bin/rundler/chain_specs/base.toml, bin/rundler/chain_specs/base_sepolia.toml, crates/builder/src/sender/mod.rs, crates/builder/src/task.rs, crates/pool/src/mempool/pool.rs, crates/sim/src/gas/gas.rs, crates/sim/src/simulation/simulator.rs, crates/types/src/chain.rs
- Modify base chain config for a new block congestion threshold and min priority fee based on recent chain usage
- Hardcode a gas limit for cancellation transactions
- Increase the timeout for KMS connections - was triggering this in local testing
- Move a few info logs to debug
- Mix missed clear in mempool
- Noticed an existing bug in the mempool with removing replaced transactions. Potentially https://github.com/alchemyplatform/rundler/issues/495, will fix in follow up PR.
=> fix: various v0.3-rc fixes

crates/pool/proto/op_pool/op_pool.proto, crates/pool/src/server/remote/error.rs, crates/rpc/src/eth/error.rs, crates/sim/src/simulation/context.rs, crates/sim/src/simulation/simulator.rs, crates/sim/src/simulation/v0_6/context.rs, crates/sim/src/simulation/v0_7/context.rs, crates/sim/src/simulation/v0_7/tracer.rs, crates/sim/tracer/src/validationTracerV0_6.ts, crates/sim/tracer/src/validationTracerV0_7.ts, crates/types/src/pool/error.rs
- Add a new simulation error for unsupported contract type
- Capture contract "header" (first 3 bytes) for each call during tracing
- If header matches the Arbitrum stylus header `0xEFF000`, add a violation
=> feat(sim): ban access to arbitrum stylus contracts during sim

.github/workflows/unit.yaml, crates/pool/src/server/local.rs, crates/sim/src/gas/gas.rs, crates/sim/src/precheck.rs
- Log pool closed error and just propagate the UnexpectedResponse error instead. We do not really want to be saying that the pool sender has closed in rpc responses
- Check that the gas price is not equal to zero before calculating the dynamic gas as this will lead to an integer overflow
=> feat(error): use unexpected error instead

bin/rundler/chain_specs/avax.toml, bin/rundler/chain_specs/bera_bartio.toml, bin/rundler/src/cli/chain_spec.rs
=> feat(chains): create bera

crates/sim/src/simulation/simulator.rs
[Closes/Fixes] #764 
- when check storage access, also failed if the entity is unstacked for new account. 
-
-
=> fix(STO-020): check entity stake for new account

bin/rundler/src/cli/builder.rs, bin/rundler/src/cli/mod.rs, bin/rundler/src/cli/node/mod.rs, bin/rundler/src/cli/pool.rs, bin/rundler/src/cli/rpc.rs, crates/builder/src/sender/mod.rs, crates/builder/src/signer/aws.rs, crates/builder/src/signer/mod.rs, crates/builder/src/task.rs, crates/pool/src/task.rs, crates/provider/src/traits/entry_point.rs, crates/rpc/src/task.rs
Closes #416 
- Modify tasks to take providers as arguments.
- Construct providers in bin in a single spot.
- This preps us for moving to Alloy providers, as there are only a few places where we will need to update. Providers, signers, and bin being the major places.
=> feat: inject providers from bin

bin/rundler/src/cli/metrics.rs, bin/rundler/src/cli/mod.rs
rundler's histgram metrics are incomplete, they miss the bucket metrics. We can only get quantile info without weights. this pr is to add buckets info. the bucket is defined as 2^x, balancing metric density and data accuracy. 
-
-
-
=> fix: add bucket to histogram metrics

.github/workflows/compliance.yaml, crates/rpc/src/debug.rs
I can't tag release/0.7 in alchemyplatform/bundler-test-executor so use master instead. since alchemyplatform/bundler-test-executor is owned by alchemy so I think it is low risk for now.
this pr also add `debug_bundler_clearReputation` endpoint. it simply calls `debug_bundler_clearState`.
=> fix failed spec test

crates/provider/src/alloy/evm.rs
- `latest` should work on all networks, and still returns the next block's base fee as per the [json-rpc spec](https://ethereum.github.io/execution-apis/api-documentation/)
=> fix(provider): use latest for fee history in pending base fee

bin/rundler/src/cli/mod.rs, crates/builder/src/bundle_proposer.rs, crates/builder/src/task.rs, crates/pool/src/task.rs, crates/provider/src/alloy/entry_point/v0_6.rs, crates/provider/src/alloy/entry_point/v0_7.rs, crates/provider/src/traits/entry_point.rs, crates/provider/src/traits/test_utils.rs, crates/rpc/src/eth/router.rs, crates/rpc/src/rundler.rs, crates/rpc/src/task.rs, crates/sim/src/estimation/estimate_call_gas.rs, crates/sim/src/estimation/estimate_verification_gas.rs, crates/sim/src/estimation/v0_6.rs, crates/sim/src/estimation/v0_7.rs, crates/sim/src/simulation/mod.rs, crates/sim/src/simulation/simulator.rs, crates/sim/src/simulation/unsafe_sim.rs, crates/sim/src/simulation/v0_6/context.rs, crates/sim/src/simulation/v0_6/tracer.rs, crates/sim/src/simulation/v0_7/context.rs, crates/sim/src/simulation/v0_7/tracer.rs, crates/types/src/user_operation/v0_6.rs, crates/types/src/user_operation/v0_7.rs
Closes: #783 
- Move usage of `max_verification_gas` and `max_simulate_handle_ops_gas` as gas limits to the entry point providers
- Add DA gas limit to the gas limit, where necessary 
- Remove unneeded PVG checks
=> feat: move limits to providers, add da to limit

crates/rpc/src/eth/error.rs
[Closes/Fixes] #794
- change error display to "{:#}" ref: https://docs.rs/anyhow/latest/anyhow/struct.Error.html#display-representations
-
-
=> feat: better output error with inner root cause.

.github/workflows/pr-lint.yaml
=> style: check pr title with commitlint

Dockerfile
Fixes #833 
- Add ca-certificates to the base ubuntu.
=> fix: install ca certificate to the base ubuntu

bin/rundler/src/cli/builder.rs, bin/rundler/src/cli/mod.rs, bin/rundler/src/cli/pool.rs, crates/builder/src/bundle_proposer.rs, crates/builder/src/bundle_sender.rs, crates/builder/src/task.rs, crates/pool/Cargo.toml, crates/pool/proto/op_pool/op_pool.proto, crates/pool/src/emit.rs, crates/pool/src/mempool/mod.rs, crates/pool/src/mempool/paymaster.rs, crates/pool/src/mempool/pool.rs, crates/pool/src/mempool/uo_pool.rs, crates/pool/src/server/remote/protos.rs, crates/pool/src/task.rs, crates/rpc/src/eth/api.rs, crates/sim/src/gas/gas.rs, crates/sim/src/lib.rs, crates/sim/src/precheck.rs, crates/types/src/da.rs, crates/types/src/pool/types.rs, docs/cli.md, test/docker-compose.yml, test/spec-tests/launchers/rundler-launcher/docker-compose.yml, test/spec-tests/launchers/rundler-launcher/rundler-launcher.sh, test/spec-tests/local/docker-compose.yml, test/spec-tests/local/launcher.sh, test/spec-tests/remote/docker-compose.yml, test/spec-tests/remote/launcher.sh
Closes #744 
- Add `da_gas_tracking_enabled` CLI parameter.
- Cache any returned DA UO data with each UO in the pool upon entry
- If tracking is enabled, on each block, pull the block data, then sync calculate the required pvg of each UO to set eligibility
- Only return eligible UOs to the builder when queried
- Repeat the sync calc in the builder ~~(can this be removed?)~~
TODO
=> feat(pool): add da tracking to pool

bin/rundler/src/cli/pool.rs, crates/pool/proto/op_pool/op_pool.proto, crates/pool/src/mempool/mod.rs, crates/pool/src/mempool/uo_pool.rs, crates/pool/src/server/remote/error.rs, crates/rpc/src/eth/error.rs, crates/types/src/pool/error.rs, crates/types/src/user_operation/mod.rs, docs/cli.md
Closes #791 
- Add a configuration option `pool.gas_limit_efficiency_reject_threshold`. If set > 0.0, the pool will check both the pre-op, and call gas limit efficiency ratios and reject if below the threshold.
- A gas limit efficiency ratio is gas used / gas limit
- Pre op gas is PVG + validation gas + paymaster validation gas.
=> feat(pool): reject UOs below configurable gas limit efficiency

crates/pool/src/mempool/paymaster.rs
- make sure we check that the paymaster tracker is enabled when calling the `check_operation_cost` function
=> feat(paymaster): look at enabled flag on check

bin/rundler/src/cli/builder.rs, bin/rundler/src/cli/mod.rs, bin/rundler/src/cli/node/mod.rs, bin/rundler/src/cli/pool.rs, bin/rundler/src/cli/rpc.rs, crates/builder/src/bundle_proposer.rs, crates/builder/src/task.rs, crates/pool/src/mempool/pool.rs, crates/pool/src/mempool/uo_pool.rs, crates/pool/src/task.rs, crates/provider/src/alloy/da/arbitrum.rs, crates/provider/src/alloy/da/local/bedrock.rs, crates/provider/src/alloy/da/local/nitro.rs, crates/provider/src/alloy/da/mod.rs, crates/provider/src/alloy/da/optimism.rs, crates/provider/src/alloy/entry_point/v0_6.rs, crates/provider/src/alloy/entry_point/v0_7.rs, crates/provider/src/alloy/mod.rs, crates/provider/src/lib.rs, crates/provider/src/traits/da.rs, crates/provider/src/traits/entry_point.rs, crates/provider/src/traits/mod.rs, crates/provider/src/traits/test_utils.rs
Closes #850 
- Split `DAGasOracle` into 2 traits
- Entrypoint only provides access to `DAGasOracle` thats typed on the UO
- `DAGasOracleSync` passed, optionally, to tasks if the chain spec supports it
=> refactor: refactor da gas provider/oracle interfaces

crates/provider/src/alloy/da/local/bedrock.rs, crates/provider/src/alloy/da/mod.rs
=>  chore(provider): add tests for da sync interface

crates/builder/src/bundle_proposer.rs, crates/pool/src/mempool/pool.rs, crates/pool/src/mempool/uo_pool.rs, crates/provider/src/alloy/da/local/bedrock.rs, crates/provider/src/alloy/da/mod.rs, crates/provider/src/traits/test_utils.rs
=> chore(pool): add tests for da/gas limit in pool

crates/builder/src/bundle_sender.rs
- Old code would always wait for the next block after a bundle was mined. Instead, if in `auto` bundling mode, we should immediately begin to build the next bundle after a bundle is mined.
=> fix(builder): don't wait for next block after bundle mine in auto

bin/rundler/chain_specs/opbnb_testnet.toml, bin/rundler/src/cli/chain_spec.rs, crates/provider/src/alloy/metrics.rs
reference: https://docs.rs/tower/latest/tower/trait.Service.html#be-careful-when-cloning-inner-services
- 
-
-
=> fix: fix middleware service clone.

.github/workflows/release.yaml
- add container github token so that we can bypass protoc rate limits
- Got this information from https://github.com/arduino/setup-protoc/issues/6
=> feat(ratelimit): adding github token to get past rate limits

crates/builder/src/bundle_sender.rs, crates/builder/src/sender/bloxroute.rs, crates/builder/src/sender/mod.rs, crates/builder/src/transaction_tracker.rs
- Handle a few more transaction sender errors that occur when the receiving node's mempool is full
=> fix(builder): handle more tx sender errors

crates/builder/src/sender/mod.rs
Picked from https://github.com/alchemyplatform/rundler/pull/920
=> fix(builder): fix reth tx sender errors

crates/builder/src/sender/mod.rs
Picked from: https://github.com/alchemyplatform/rundler/pull/928
=> fix(builder): order sender error match by most specific first

crates/pool/src/chain.rs
- Add sync error counter to the chain tracker to catch the edge case where the chain will always get stopped at the `ensure!` macro where the current head is much larger than the new head
=> feat(chain): add a sync error count to reset in edge cases

crates/pool/src/chain.rs
- cherry pick from 6b9a2ad4b97666bd85a527ebaee47c7d0eac1b07
=> feat(chain): add a sync error count to reset in edge cases (#922)

crates/builder/src/sender/bloxroute.rs, crates/builder/src/sender/mod.rs
[Closes/Fixes] # https://github.com/alchemyplatform/rundler/issues/925
- Use error codes -32003 and -32005 when condition is not met on eth_sendRawTransactionConditional https://eips.ethereum.org/EIPS/eip-7796 (instead of string matching on json rpc error message)
- Tests
=> feat(Rundler): Handle standardized eth_sendRawTransactionConditional error codes

Cargo.lock, Cargo.toml, bin/rundler/Cargo.toml, bin/rundler/src/cli/rpc.rs, crates/rpc/Cargo.toml, crates/rpc/src/task.rs, docs/cli.md
[Closes/Fixes] #579 
* Implementing the cors that is already written for tower-http.
This is before the cors implementation
Then adding the `RPC_CORSDOMAIN=*` fix we get
This is from 127.0.0.1:3000, notice no cors in response
This is from localhost:3000, notice again cors
Then we set the `RPC_CORSDOMAIN=http://127.0.0.1:3000`
Then we set the `RPC_CORSDOMAIN=http://127.0.0.1:3000,http://localhost:3000` Testing list of domains
And when we add a wildcard at the end `RPC_CORSDOMAIN=http://127.0.0.1:3000,http://localhost:3000,*`
we throw on reading the env
And with corsdomain as localhost
```js
fetch("http://127.0.0.1:3000/", {
method: 'POST',
mode: 'cors',
headers: { 'Content-Type': 'application/json' },
body: JSON.stringify({
jsonrpc: '2.0',
method: 'system_health',
id: 1
})
}).then(res => { …
```
=> feat(Rundler): Add cors to the server

crates/pool/src/mempool/pool.rs, crates/pool/src/mempool/uo_pool.rs, crates/sim/src/lib.rs, crates/sim/src/precheck.rs
- Use the same logic as the builder to determine candidate status in the mempool
=> fix(pool): fix pool candidates metrics to align with builder

crates/builder/src/bundle_proposer.rs, crates/builder/src/bundle_sender.rs, crates/builder/src/task.rs, crates/provider/src/alloy/entry_point/v0_6.rs, crates/provider/src/alloy/entry_point/v0_7.rs, crates/provider/src/traits/entry_point.rs, crates/provider/src/traits/test_utils.rs
- Bundle simulation should include (1) fees (2) sender EOA
- Fixes a bug where if the fees are not set then the EVM base fee is set to 0, which impacts final simulation
=> fix(builder): set fees during bundle sim to ensure base fee is applied

Cargo.lock, Cargo.toml
This PR bumps the `reth-tasks` dependency in `rundler` to `v1.1.4`. This makes `rundler` crates that have `reth-tasks` as a dependency compatible with projects depending on the latest version of Reth.
=> chore: bump reth deps

.github/workflows/compliance.yaml, .github/workflows/compliance_v06.yaml, crates/pool/src/mempool/pool.rs, crates/pool/src/mempool/reputation.rs, crates/pool/src/mempool/uo_pool.rs
Fixes: #958
- Consider replacements during max ops per sender enforcement
- A few small tweaks to reputation logic
=> fix(pool): fix pool max ops per sender during replacement

.github/workflows/compliance.yaml, .github/workflows/compliance_v06.yaml, Cargo.lock, Cargo.toml, bin/rundler/src/cli/builder.rs, bin/rundler/src/cli/mod.rs, crates/builder/src/bundle_proposer.rs, crates/builder/src/bundle_sender.rs, crates/builder/src/sender/mod.rs, crates/builder/src/task.rs, crates/builder/src/transaction_tracker.rs, crates/pool/src/mempool/pool.rs, crates/pool/src/mempool/reputation.rs, crates/pool/src/mempool/uo_pool.rs, crates/provider/Cargo.toml, crates/provider/src/alloy/entry_point/v0_6.rs, crates/provider/src/alloy/entry_point/v0_7.rs, crates/provider/src/alloy/metrics.rs, crates/provider/src/alloy/mod.rs, crates/provider/src/alloy/provider_timeout.rs, crates/provider/src/traits/entry_point.rs, crates/provider/src/traits/test_utils.rs, crates/sim/src/lib.rs, crates/sim/src/precheck.rs, crates/types/src/task/status_code.rs
- https://github.com/alchemyplatform/rundler/pull/943
- https://github.com/alchemyplatform/rundler/pull/926
- https://github.com/alchemyplatform/rundler/pull/947
- Not a direct pick of: https://github.com/alchemyplatform/rundler/pull/940
- v0.4 is missing the EREP-040 amendment code, so this was modified, end result is the same.
- https://github.com/alchemyplatform/rundler/pull/965
- https://github.com/alchemyplatform/rundler/pull/966
- https://github.com/alchemyplatform/rundler/pull/951
=> fix: pick various v0.4 fixes from main

bin/rundler/src/cli/pool.rs, crates/pool/src/mempool/mod.rs, crates/pool/src/mempool/pool.rs, crates/pool/src/mempool/uo_pool.rs, crates/types/src/timestamp.rs, docs/cli.md
Closes #936
- Add a configurable maximum amount of time a UO is allowed to be in the pool. Defaults to disabled.
=> feat(pool): add a configurable maximum time allowed in pool

crates/rpc/src/types/mod.rs, crates/rpc/src/types/rpc_authorization.rs, crates/rpc/src/types/v0_6.rs, crates/rpc/src/types/v0_7.rs
=> fix: change authorization tuple use hexstirng

crates/pool/src/mempool/pool.rs, crates/pool/src/mempool/uo_pool.rs
=> feat(pool): update best price on base fee change

Dockerfile, bin/rundler/src/cli/pool.rs, crates/pool/proto/op_pool/op_pool.proto, crates/pool/src/mempool/mod.rs, crates/pool/src/mempool/pool.rs, crates/pool/src/mempool/uo_pool.rs, crates/pool/src/server/remote/error.rs, crates/pool/src/server/remote/protos.rs, crates/provider/src/alloy/entry_point/v0_6.rs, crates/provider/src/alloy/entry_point/v0_7.rs, crates/rpc/src/eth/error.rs, crates/rpc/src/types/rpc_authorization.rs, crates/rpc/src/types/v0_6.rs, crates/rpc/src/types/v0_7.rs, crates/sim/src/estimation/estimate_call_gas.rs, crates/sim/src/estimation/v0_6.rs, crates/sim/src/estimation/v0_7.rs, crates/types/src/authorization.rs, crates/types/src/pool/error.rs, crates/types/src/user_operation/mod.rs, crates/types/src/user_operation/v0_6.rs, crates/types/src/user_operation/v0_7.rs, crates/utils/src/authorization_utils.rs
[Closes/Fixes] #969
follow this to finalize 7702 api
https://docs.google.com/document/d/1w3xB_B1PUYRDnnCXSsLZXQVerjiw0_72NxvQwhdrWeU/edit?tab=t.0#heading=h.gofdrsh0t6jb
-
-
-
=> feat(7702): use standardized eip7702_auth

crates/pool/src/mempool/uo_pool.rs
=> fix(pool): fix execution gas eff check for v0.6 with paymasters

crates/pool/src/mempool/uo_pool.rs
- ERC-7562 relaxed this requirement, we're finally catching up
=> feat(pool): allow multiple UOs from an unstaked sender in a bundle

Cargo.lock, Cargo.toml, bin/rundler/Cargo.toml, crates/pool/Cargo.toml, crates/pool/src/mempool/pool.rs, crates/pool/src/mempool/uo_pool.rs, crates/pool/src/server/remote/protos.rs, crates/provider/src/alloy/entry_point/mod.rs, crates/provider/src/alloy/entry_point/v0_6.rs, crates/provider/src/alloy/entry_point/v0_7.rs, crates/rpc/Cargo.toml, crates/types/src/authorization.rs, crates/types/src/user_operation/mod.rs, crates/types/src/user_operation/v0_6.rs, crates/types/src/user_operation/v0_7.rs, crates/utils/src/random.rs
=> fix(7702): add max_fill, random_fill, and use for gas estimation

.github/workflows/release.yaml
- Pin rust version
- Update the macos runner for x86 runners
turns out github made a change and now the `macos-latest` runner only supports arm64 as all their new apple machines are arm. I changed the intel runner to `macos-13` to fix the bug when trying to install the rust std lib.
https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
=> feat(ci): fix release runner

Cargo.lock, bin/rundler/src/cli/builder.rs, bin/rundler/src/cli/mod.rs, crates/builder/src/bundle_proposer.rs, crates/builder/src/bundle_sender.rs, crates/builder/src/emit.rs, crates/builder/src/task.rs, crates/pool/Cargo.toml, crates/pool/proto/op_pool/op_pool.proto, crates/pool/src/mempool/mod.rs, crates/pool/src/mempool/paymaster.rs, crates/pool/src/mempool/pool.rs, crates/pool/src/mempool/uo_pool.rs, crates/pool/src/server/local.rs, crates/pool/src/server/remote/client.rs, crates/pool/src/server/remote/protos.rs, crates/pool/src/server/remote/server.rs, crates/pool/src/task.rs, crates/rpc/src/eth/api.rs, crates/sim/src/simulation/mempool.rs, crates/types/src/pool/traits.rs, crates/types/src/pool/types.rs, docs/architecture/builder.md, docs/architecture/pool.md
=> feat: add mempool filters and builder affinity

Cargo.lock, bin/rundler/Cargo.toml, bin/rundler/src/cli/proxy.rs, crates/aggregators/pbh/Cargo.toml, crates/aggregators/pbh/src/proxy.rs, crates/builder/src/bundle_proposer.rs, crates/provider/src/alloy/entry_point/v0_6.rs, crates/provider/src/alloy/entry_point/v0_7.rs, crates/provider/src/traits/entry_point.rs, crates/types/src/proxy.rs, crates/types/src/user_operation/mod.rs, docs/architecture/builder.md
- Pass non-entrypoint revert data to proxies, if they exist
- Remove UOs from the pool if notified by proxy
- Else, remove all UOs from the pool if the fault is not attributable to avoid infinite failure loops
=> feat(builder): process reverts through proxies, removing ops

crates/builder/src/bundle_proposer.rs, crates/builder/src/bundle_sender.rs, crates/builder/src/transaction_tracker.rs
=> feat(builder): add more builder metrics for latency tracking

Makefile, crates/aggregators/pbh/src/pbh.rs, crates/builder/src/bundle_proposer.rs, crates/builder/src/bundle_sender.rs, crates/pool/src/mempool/mod.rs, crates/pool/src/mempool/paymaster.rs, crates/pool/src/mempool/pool.rs, crates/pool/src/mempool/uo_pool.rs, crates/pool/src/server/remote/protos.rs, crates/provider/src/alloy/entry_point/mod.rs, crates/provider/src/alloy/entry_point/v0_6.rs, crates/provider/src/alloy/entry_point/v0_7.rs, crates/rpc/src/eth/api.rs, crates/rpc/src/eth/events/common.rs, crates/rpc/src/eth/events/v0_6.rs, crates/rpc/src/types/v0_6.rs, crates/rpc/src/types/v0_7.rs, crates/sim/src/estimation/estimate_call_gas.rs, crates/sim/src/estimation/v0_6.rs, crates/sim/src/estimation/v0_7.rs, crates/sim/src/precheck.rs, crates/sim/src/simulation/simulator.rs, crates/sim/src/simulation/v0_6/context.rs, crates/types/src/user_operation/mod.rs, crates/types/src/user_operation/v0_6.rs, crates/types/src/user_operation/v0_7.rs
- Modify UO interfaces to remove all public members such that modifications must go through the builder.
- This ensures that modifications update any cached values - hash, packed, calldata cost, etc.
- Cleanup v0.6 builder pattern
- Most of the PR changes are to tests, as these we're the biggest offenders of modifying UOs incorrectly.
=> feat: cleanup uo interface to be safer to modifications

bin/rundler/src/cli/proxy.rs, crates/aggregators/pbh/src/proxy.rs, crates/builder/src/bundle_proposer.rs, crates/builder/src/bundle_sender.rs, crates/builder/src/task.rs, crates/contracts/src/v0_7.rs, crates/provider/src/alloy/entry_point/v0_6.rs, crates/provider/src/alloy/entry_point/v0_7.rs, crates/provider/src/lib.rs, crates/provider/src/traits/entry_point.rs, crates/provider/src/traits/test_utils.rs, crates/rpc/src/eth/events/v0_6.rs, crates/rpc/src/eth/events/v0_7.rs, crates/types/src/proxy.rs
Closes #990 
- Get the revert data from reverted transactions using debug_traceTransaction
- Decode the revert data and the UOs from the transaction
- Figure out which UO caused the revert and remove, if cannot determine, remove all UOs
TODO:
=> feat(builder): remove offending UOs after onchain revert

bin/rundler/src/cli/mod.rs, bin/rundler/src/cli/node/mod.rs, bin/rundler/src/cli/rpc.rs, crates/builder/src/bundle_proposer.rs, crates/pool/proto/op_pool/op_pool.proto, crates/pool/src/mempool/mod.rs, crates/pool/src/mempool/paymaster.rs, crates/pool/src/mempool/pool.rs, crates/pool/src/mempool/uo_pool.rs, crates/pool/src/server/local.rs, crates/pool/src/server/remote/client.rs, crates/pool/src/server/remote/protos.rs, crates/pool/src/server/remote/server.rs, crates/rpc/src/eth/api.rs, crates/rpc/src/eth/mod.rs, crates/rpc/src/eth/server.rs, crates/rpc/src/task.rs, crates/rpc/src/types/mod.rs, crates/rpc/src/types/permissions.rs, crates/rpc/src/types/v0_6.rs, crates/sim/src/simulation/mod.rs, crates/sim/src/simulation/simulator.rs, crates/sim/src/simulation/unsafe_sim.rs, crates/types/src/pool/traits.rs, crates/types/src/pool/types.rs, crates/types/src/user_operation/mod.rs, crates/types/src/user_operation/permissions.rs, crates/types/src/user_operation/v0_7.rs, docs/architecture/rpc.md, docs/cli.md
- Add an optional field to the end of `eth_sendUserOperation` to represent user operation permissions
- Add the first permission, trusted, which allows the UO to use unsafe simulation
TODO:
=> feat: add uo perms and trusted uo submission

crates/builder/src/bundle_proposer.rs, crates/pool/proto/op_pool/op_pool.proto, crates/pool/src/mempool/uo_pool.rs, crates/pool/src/server/remote/protos.rs, crates/rpc/src/types/permissions.rs, crates/types/src/user_operation/permissions.rs, docs/architecture/rpc.md
- Add a new permissions to allow more max allowed UOs in the pool for trusted senders
TODO:
=> feat: add max uo per sender permission

Cargo.lock, Cargo.toml, crates/builder/src/transaction_tracker.rs, crates/contracts/contracts/src/utils/GetBalances.sol, crates/contracts/src/utils.rs, crates/pool/Cargo.toml, crates/pool/src/chain.rs, crates/provider/Cargo.toml, crates/provider/src/alloy/da/arbitrum.rs, crates/provider/src/alloy/da/local/bedrock.rs, crates/provider/src/alloy/da/local/nitro.rs, crates/provider/src/alloy/da/mod.rs, crates/provider/src/alloy/da/optimism.rs, crates/provider/src/alloy/entry_point/v0_6.rs, crates/provider/src/alloy/entry_point/v0_7.rs, crates/provider/src/alloy/evm.rs, crates/provider/src/alloy/mod.rs, crates/provider/src/lib.rs, crates/provider/src/traits/evm.rs, crates/provider/src/traits/test_utils.rs, crates/rpc/src/eth/api.rs, crates/rpc/src/eth/events/mod.rs
- Add `get_full_block` and `get_balances` to `EvmProvider`
- For `get_full_block`: alloy requires the use of `AnyNetwork` to deserialize blocks for any network, else we'd get errors deserializing arbitrum, optimism, etc blocks.
- Modify the provider crate and types to use `AnyNetwork`
=> feat(provider): use anynetwork, add get full block/get balances

Cargo.lock, Cargo.toml, crates/builder/src/bundle_sender.rs, crates/pool/Cargo.toml, crates/pool/proto/op_pool/op_pool.proto, crates/pool/src/chain.rs, crates/pool/src/mempool/mod.rs, crates/pool/src/mempool/uo_pool.rs, crates/pool/src/server/local.rs, crates/pool/src/server/remote/client.rs, crates/pool/src/server/remote/protos.rs, crates/pool/src/server/remote/server.rs, crates/pool/src/task.rs, crates/rpc/src/debug.rs, crates/task/src/block_watcher.rs, crates/types/src/pool/traits.rs, crates/types/src/pool/types.rs, crates/utils/src/retry.rs
- Modify new heads subscription to pass addresses to track
- Track addresses during chain tracking, adding address updates from any of the tracked addresses
- Address updates contains latest nonce, balance, and any mined transaction hashes
=> feat(pool): add address tracking to pool

crates/rpc/src/eth/events/common.rs, crates/rpc/src/eth/events/mod.rs, crates/rpc/src/eth/events/v0_6.rs, crates/rpc/src/eth/events/v0_7.rs, crates/rpc/src/eth/router.rs, crates/rpc/src/rundler.rs, crates/rpc/src/task.rs, crates/rpc/src/types/mod.rs, docs/architecture/rpc.md
Closes #1044
- Adds `rundler_getMinedUserOperation`
- Refactors some of the event code for reuse with the new RPC call
=> feat(rpc): add rundler_getMinedUserOperation

crates/builder/src/bundle_proposer.rs, crates/pool/proto/op_pool/op_pool.proto, crates/pool/src/mempool/pool.rs, crates/pool/src/mempool/uo_pool.rs, crates/pool/src/server/remote/protos.rs, crates/rpc/src/eth/server.rs, crates/rpc/src/types/permissions.rs, crates/sim/src/precheck.rs, crates/types/src/user_operation/permissions.rs, crates/utils/src/math.rs, docs/architecture/rpc.md
- Add two new permissions: one for relaxing fee check for acceptance to the pool, one for relaxing fee check for bundling
TODO
=> feat: add permission for relaxed fee checking

crates/builder/src/bundle_sender.rs
Picked from https://github.com/alchemyplatform/rundler/pull/1073
=> fix(builder): fix unlimited span causing memory build with OTLP

bin/rundler/src/cli/mod.rs, bin/rundler/src/cli/rpc.rs, crates/rpc/src/eth/api.rs, crates/rpc/src/eth/events/common.rs, crates/rpc/src/eth/mod.rs, crates/rpc/src/task.rs, crates/sim/src/simulation/mod.rs, crates/sim/src/simulation/simulator.rs, docs/cli.md
- Adds 2 new CLI variables
- `enable_unsafe_fallback` - allows simulation to fallback to unsafe mode if the tracer is failing
- `user_operation_event_block_distance_fallback` - allows RPC to fallback to a shorter distance if get_logs is failing
=> feat: enable fallbacks for common RPC provider differences

crates/builder/src/bundle_sender.rs, crates/builder/src/server/local.rs, crates/builder/src/transaction_tracker.rs, crates/pool/proto/op_pool/op_pool.proto, crates/pool/src/chain.rs, crates/types/src/pool/types.rs
- Fixes a bug in `bundle_sender` where its view of its own balance becomes stale after a funding event. Prior to this change, it would only be notified of a balance change if its own nonce changed. This doesn't handle funding events.
- The fix is to add an address update for every tracked address on every new block. This adds one new always-performed parallel call to the chain tracking logic.
- Address update now has an optional nonce indicating that it nonce changed, else None.
=> fix(builder): fix sender balance tracking to capture funding events

crates/builder/src/bundle_proposer.rs, crates/provider/src/alloy/entry_point/v0_6.rs, crates/provider/src/alloy/entry_point/v0_7.rs, crates/provider/src/traits/entry_point.rs, crates/provider/src/traits/test_utils.rs
Closes #903
- Skip bundle simulation if v0.7+ and there is only one UO in the bundle. This simulation was just performed.
- If v0.7+ add a reverting UO as the last index in the bundle to skip the execution portion during simulation as it doesn't impact bundle validity.
=> feat(builder): for v0.7+ only run the validation portion during bundle sim

crates/contracts/build.rs, crates/contracts/contracts/v0_7/src/EntryPointSimulations.sol, crates/contracts/contracts/v0_7/src/imports.sol, crates/contracts/src/v0_7.rs, crates/provider/src/alloy/entry_point/v0_6.rs, crates/provider/src/alloy/entry_point/v0_7.rs, crates/provider/src/traits/entry_point.rs, crates/provider/src/traits/test_utils.rs, crates/sim/src/estimation/estimate_call_gas.rs, crates/sim/src/estimation/estimate_verification_gas.rs, crates/sim/src/estimation/v0_6.rs, crates/sim/src/estimation/v0_7.rs
- Rundler v0.8 had a change where we clear paymasters during call gas estimation. See https://github.com/alchemyplatform/rundler/pull/1130
- We since learned that some account implementations may look at the paymaster and paymaster data during their validation functions. Clearing this paymaster could cause validation to fail.
- This clearing was done in order to skip running the paymaster's `postOp` function as it may have side effects that impact the gas estimation done as part of the target call in `simulateHandleOp`. Onchain, `postOp` always runs after the execution, so me must not run it before its estimation.
- The fix is to modify `simulateHandleOp` to skip the `postOp` call (by clearing the `context` on `opInfo`).
=> fix(sim): remove paymaster clear and skip postop in v0.7 estimation

crates/pool/proto/op_pool/op_pool.proto, crates/pool/src/mempool/mod.rs, crates/pool/src/mempool/uo_pool.rs, crates/pool/src/server/local.rs, crates/pool/src/server/remote/client.rs, crates/pool/src/server/remote/server.rs, crates/rpc/src/rundler.rs, crates/types/src/pool/traits.rs, docs/architecture/rpc.md
- Add new RPC method `rundler_getPendingUserOperationBySenderNonce`
- See `rpc.md` for description
=> feat(rpc): add get pending user operation by sender nonce RPC

bin/rundler/src/cli/mod.rs, crates/contracts/contracts/v0_7/src/VerificationGasEstimationHelper.sol, crates/contracts/src/v0_7.rs, crates/sim/src/estimation/estimate_verification_gas.rs, crates/sim/src/estimation/mod.rs, crates/sim/src/estimation/v0_6.rs, crates/sim/src/estimation/v0_7.rs, docs/architecture/builder.md, docs/cli.md
- Also use `MAX_GAS_ESTIMATION_GAS` during VGL/PVGL estimation
=> fix(sim): fix paymaster data parsing during constant fee logic in gas estimation

bin/rundler/chain_specs/base.toml, bin/rundler/src/cli/builder.rs, bin/rundler/src/cli/mod.rs, crates/types/src/chain.rs
- Add a new transaction gas limit field to chain spec
- Add a function to chain spec to resolve the maximum transaction gas between the txn limit and the block limit
- [BREAKING] Modify the names of the CLI parameters to control the bundle gas limits
=> feat(chain): add transaction gas limit and modify CLI to use it for bundle limits
